# Generated by Django 3.2.8 on 2021-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogramapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogramdetails',
            name='data_point',
            field=models.JSONField(),
        ),
    ]
